### ISSUE TITLE
Random Error: "MaxBufferError: stdout maxBuffer exceeded"

### ISSUE THREAD

**Issue by ChenfengWei1** [chenzhutian/hexo-all-minifier#110]
Hello,

I have been using this plugin for a while and am very grateful for your work.

However, there is an inevitable random error when deploying my `hexo page`. This bug, which has been shown below, would lead to a failure of deployment:

![MaxBufferErro](https://user-images.githubusercontent.com/40056004/132417900-17e56360-c04f-4f73-9044-ce8c46cb461b.png)

sys:
- os: wsl-ubuntu 20.04 distribution
- node: v12.22.6
- hexo 5.4.0

conf:
```yml
all_minifier: true
js_concator:
  enable: false

html_minifier:
  enable: true 
  collapseBooleanAttributes: false
  collapseWhitespace: true
  removeComments: true
  removeEmptyAttributes: true
  removeScriptTypeAttributes: false
  removeStyleLinkTypeAttributes: false
  minifyJS: false
  minifyCSS: false
  ignore_error: false
  silent: false
  exclude:

css_minifier:
  enable: true
  exclude: 
    - '*.min.css'

js_minifier:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - "*.min.js"
    - "ins.js"
    - "ins.ejs"

image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: true
  progressive: false
  silent: false
```

Somehow, I managed to solve this problem by adding a 'exclude' part in the 'image_minifer' section. 

```yml
  exclude: 
    - "*.jpg"
    - "*.gif"
```

Both `jpg` and `gif` files have been filtered and somehow it worked. So I just want to report this bug and its potential solution, notwithstanding I have no idea of its cause.
